inhibit_all_warnings!

use_frameworks!
target 'nicefilm_swift' do
    pod 'SnapKit', '~> 4.0.0'
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON', '~> 4.0.0'
    pod 'ObjectMapper', '~> 3.1'
    pod 'Toaster', '~> 2.1.1'
    pod 'Kingfisher', '~> 4.2.0'
    pod 'CryptoSwift', '~>  0.8.0'
    pod 'Moya',     '~> 10.0'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'Moya/RxSwift', '~> 10.0'
    
end
